version: '3.8'

volumes:
  postgres_data:
  static_volume: 
  media_volume: 

services:  
  db:
    image: postgres:latest
    #Всегда стоит явно указывать версию - выйдет новая, твой продакшн обновится и упадет изза несовместимости.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - database_network  
    env_file:
      - ./.env
  web:
   
    image: svetlana1905/foodgram:latest
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000    
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    networks: 
      - nginx_network 
      - database_network
    depends_on:
      - db
    env_file:
      - ./.env       
    
  nginx:
    image: nginx:latest
    restart: always  
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/etc/nginx/templates/static
      - media_volume:/etc/nginx/templates/media      
    ports:
      - "80:80"  
    depends_on:
      - web    
    networks:  
      - nginx_network  

networks:  
  nginx_network:
    driver: bridge  
  database_network:
    driver: bridge   